version: '3.9'

services:
  mongodb:
    container_name: mongodb_container
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  nodejs:
    container_name: nodejs_container
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      MONGO_URL: mongodb://mongo:27017/coderhouse

volumes:
  mongodb_data:
    driver: local
      


      