# Utilizamos una imagen base de Node.js
FROM node:latest

# Establecemos el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiamos el archivo package.json y package-lock.json (si existe)
COPY package*.json ./

# Instalamos las dependencias del proyecto
RUN npm install

# Copiamos el resto de los archivos del proyecto
COPY . .

# Exponemos el puerto en el que la aplicación va a correr
EXPOSE 8080

# Comando para ejecutar la aplicación
CMD ["npm", "start"]